### ISSUE TITLE
Board resize to 0 width and/or 0 height pushes tickets out of bounds

### ISSUE THREAD

**Issue by Temetz** [N4SJAMK/teamboard-api#22]
If user makes a API request to resize the board to 0. All tickets will be pushed out of the boads. Tickets are still part of the board but cannot be accessed / are not visible to user.

![image](https://cloud.githubusercontent.com/assets/8721037/8108346/82038eba-1058-11e5-8093-a61ba6408969.png)

**Comment by tanelih** [comment]
Setting the board width or height to 0 should result in a bad request I guess. We can set the `min` and `max` values in the board schema.
